//
// Created by bleppe on 11/05/23.
//

#ifndef LCDTEST_CONTROLLERINPUTEVENT_H
#define LCDTEST_CONTROLLERINPUTEVENT_H

#include "input.h"

enum ControlType {
    CONTROL_TYPE_INVALID = 0,
    CONTROL_TYPE_ENTER,
    CONTROL_TYPE_RETURN,
    CONTROL_TYPE_CANCEL,
    CONTROL_TYPE_OPTION,
    CONTROL_TYPE_UP,
    CONTROL_TYPE_DOWN,
    CONTROL_TYPE_PUMP,
    CONTROL_TYPE_SPACE,
};

enum InputEventType {
    INPUT_EVENT_TYPE_ALPHA = 0,
    INPUT_EVENT_TYPE_NUMERIC,
    INPUT_EVENT_TYPE_SYMBOL,
    INPUT_EVENT_TYPE_CONTROL,
};

class ControllerInputEvent {
public:
    InputEventType type;
    int code;
    INPUT_EVENTS event;
};


#endif //LCDTEST_CONTROLLERINPUTEVENT_H
